"""ATLAS-103: staged planner prompt templates.

Three per-stage templates (epics / tickets-per-epic / dependencies) are
projections of the §3.11 proposal contract, assembled by ATLAS-104 into
one full-state proposal (planning-large-corpora.md §4/§4.1, ADR-0010).
This ticket builds the template ARTIFACTS only — these tests assert each
renders deterministically through the EXISTING renderer, fails closed on
missing/extra variables, carries the stage's projection instruction and
the environment-owns-identity rule, and that the live single-call path
is structurally protected and unchanged.

The fixture schema is clearly labelled: the real per-stage projection
schema is caller-supplied (ATLAS-104 generates it; the renderer's D2
seam). Templates are selected by explicit ``version=`` — ATLAS-104's job;
this ticket just makes them selectable.
"""

import hashlib
from collections.abc import Callable
from pathlib import Path

import pytest

from atlas.planning import (
    MissingVariableError,
    SourceDocument,
    UndeclaredVariableError,
    current_release,
    render_planner_prompt,
)
from atlas.planning.renderer import CurrentReleaseError

FIXTURE_SCHEMA = (
    '{"$comment": "FIXTURE per-stage projection schema - generated by ATLAS-104"}'
)

VariablesFactory = Callable[[], dict[str, object]]

EPICS_VERSION = "planner-stage-epics-v1.0.0"
EPICS_V1_1_0_VERSION = "planner-stage-epics-v1.1.0"
EPICS_V1_2_0_VERSION = "planner-stage-epics-v1.2.0"
TICKETS_VERSION = "planner-stage-tickets-v1.0.0"
TICKETS_V1_1_0_VERSION = "planner-stage-tickets-v1.1.0"
TICKETS_V1_2_0_VERSION = "planner-stage-tickets-v1.2.0"
TICKETS_V1_3_0_VERSION = "planner-stage-tickets-v1.3.0"
TICKETS_V1_4_0_VERSION = "planner-stage-tickets-v1.4.0"
TICKETS_V1_5_0_VERSION = "planner-stage-tickets-v1.5.0"
TICKETS_V1_6_0_VERSION = "planner-stage-tickets-v1.6.0"
DEPENDENCIES_VERSION = "planner-stage-dependencies-v1.0.0"

# A retained prior single-call template (no longer the live release since
# ATLAS-111 bumped CURRENT to planner-v1.2.0): pin its file bytes so the
# retained artifact is never edited in place — historical PlanRuns reproduce.
SINGLE_CALL_VERSION = "planner-v1.1.0"
SINGLE_CALL_FILE_SHA256 = (
    "8e4e4a4aaf9a547595954524aede0db8f45f7cf1ebd99a825c5c53141369208f"
)

DOCUMENTS = [
    SourceDocument(path="docs/a.md", sha="sha-aaa", content="# A\n"),
    SourceDocument(path="docs/b.md", sha="sha-bbb", content="# B\n"),
]

# The valid-anchor list payload (ATLAS-111): {anchor, heading} dicts, as the
# pipeline derives from AnchorIndex.anchor_choices().
VALID_ANCHORS = [
    {"anchor": "docs/a.md#a", "heading": "A"},
    {"anchor": "docs/b.md#b", "heading": "B"},
]


def epics_variables() -> dict[str, object]:
    return {
        "product_key": "ATLAS",
        "documents": DOCUMENTS,
        "stage_output_schema": FIXTURE_SCHEMA,
    }


def tickets_variables() -> dict[str, object]:
    return {
        "product_key": "ATLAS",
        "documents": DOCUMENTS,
        "epic": {
            "title": "Planning Engine",
            "objective": "Generate a backlog",
            "description": "The plan/apply loop",
        },
        "epic_index": "new_epic:0",
        "assembled_epics": [
            {"index": "new_epic:0", "title": "Planning Engine"},
            {"index": "new_epic:1", "title": "Dependency Engine"},
        ],
        "stage_output_schema": FIXTURE_SCHEMA,
    }


def dependencies_variables() -> dict[str, object]:
    return {
        "product_key": "ATLAS",
        "documents": DOCUMENTS,
        "assembled_tickets": [
            {"index": "new:0", "title": "Document ingestion", "epic_ref": "new_epic:0"},
            {"index": "new:1", "title": "Reconciler", "epic_ref": "new_epic:0"},
        ],
        "stage_output_schema": FIXTURE_SCHEMA,
    }


STAGES = (
    pytest.param(EPICS_VERSION, epics_variables, id="epics"),
    pytest.param(TICKETS_VERSION, tickets_variables, id="tickets"),
    pytest.param(DEPENDENCIES_VERSION, dependencies_variables, id="dependencies"),
)


# --- each staged template renders deterministically with a stable hash -------


@pytest.mark.parametrize("version, variables", STAGES)
def test_staged_template_renders_deterministically(
    version: str, variables: VariablesFactory
) -> None:
    first = render_planner_prompt(variables(), version=version)
    second = render_planner_prompt(variables(), version=version)
    assert first.text == second.text
    assert first.prompt_version == version
    assert first.template.stage == {
        EPICS_VERSION: "epics",
        TICKETS_VERSION: "tickets",
        DEPENDENCIES_VERSION: "dependencies",
    }[version]


@pytest.mark.parametrize("version, variables", STAGES)
def test_staged_prompt_hash_is_sha256_of_text(
    version: str, variables: VariablesFactory
) -> None:
    rendered = render_planner_prompt(variables(), version=version)
    expected = hashlib.sha256(rendered.text.encode("utf-8")).hexdigest()
    assert rendered.prompt_hash == expected


@pytest.mark.parametrize("version, variables", STAGES)
def test_staged_template_embeds_caller_supplied_schema(
    version: str, variables: VariablesFactory
) -> None:
    text = render_planner_prompt(variables(), version=version).text
    assert FIXTURE_SCHEMA in text


# --- variable validation: fail closed in both directions ---------------------


@pytest.mark.parametrize("version, variables", STAGES)
def test_each_missing_declared_variable_fails_before_render(
    version: str, variables: VariablesFactory
) -> None:
    for name in list(variables()):
        broken = variables()
        del broken[name]
        with pytest.raises(MissingVariableError, match=name):
            render_planner_prompt(broken, version=version)


@pytest.mark.parametrize("version, variables", STAGES)
def test_undeclared_extra_variable_fails(
    version: str, variables: VariablesFactory
) -> None:
    with pytest.raises(UndeclaredVariableError, match="surprise"):
        render_planner_prompt(variables() | {"surprise": 1}, version=version)


# --- product_key earns its place: it appears in the role framing -------------


@pytest.mark.parametrize("version, variables", STAGES)
def test_product_key_appears_in_role_framing(
    version: str, variables: VariablesFactory
) -> None:
    rendered = render_planner_prompt(
        variables() | {"product_key": "ZEBRA"}, version=version
    )
    role = rendered.text.split("# Inputs", 1)[0]
    assert "ZEBRA" in role, "product_key must appear in the rendered role framing"


# --- each stage carries its §3.11 projection instruction ---------------------


def test_epics_stage_projection_is_epics_only() -> None:
    text = render_planner_prompt(epics_variables(), version=EPICS_VERSION).text
    assert "**Epics only.**" in text
    # The epics slice composes into the §3.11 envelope; not tickets/deps here.
    assert "Do NOT emit tickets or dependencies" in text


def test_tickets_stage_projection_is_tickets_for_one_epic() -> None:
    text = render_planner_prompt(tickets_variables(), version=TICKETS_VERSION).text
    assert "**Tickets for this epic only.**" in text
    # epic_ref carries the given new_epic:<n>, composing into the envelope.
    assert '"epic_ref": "new_epic:0"' in text
    assert "Do NOT emit epics or dependencies" in text


def test_dependencies_stage_projection_is_dependencies_only() -> None:
    text = render_planner_prompt(
        dependencies_variables(), version=DEPENDENCIES_VERSION
    ).text
    assert "**Dependencies only.**" in text
    # Edges reference the environment-assigned new:<n> indices.
    assert "new:0" in text and "new:1" in text
    assert "Do NOT emit epics or tickets" in text


# --- each stage carries the environment-owns-identity rule (no minting) ------


def test_epics_stage_forbids_minting_epic_indices() -> None:
    text = render_planner_prompt(epics_variables(), version=EPICS_VERSION).text
    assert "The environment owns identity — you never mint it." in text
    assert "or invent `new_epic:<n>` indices" in text
    assert "by your emission order" in text


def test_tickets_stage_forbids_numbering_tickets() -> None:
    text = render_planner_prompt(tickets_variables(), version=TICKETS_VERSION).text
    assert "The environment owns identity — you never mint it." in text
    assert "tickets or invent `new:<n>` indices" in text
    assert "by its position in the assembled tickets array" in text


def test_dependencies_stage_forbids_minting_ticket_identity() -> None:
    text = render_planner_prompt(
        dependencies_variables(), version=DEPENDENCIES_VERSION
    ).text
    assert "The environment owns identity — you never mint it." in text
    assert "renumber, or create ticket identities." in text


# --- the live single-call path: structurally protected and unchanged ---------


def test_current_release_is_a_single_call_template() -> None:
    # CURRENT names a single-call release (planner-v1.2.0 since ATLAS-111), never
    # a staged name; the staged set is selected only by explicit version=.
    assert current_release() == "planner-v1.2.0"


def test_single_call_template_file_is_byte_for_byte_unchanged() -> None:
    from atlas.planning.renderer import PROMPTS_DIR

    path = PROMPTS_DIR / f"{SINGLE_CALL_VERSION}.md.j2"
    actual = hashlib.sha256(path.read_bytes()).hexdigest()
    assert actual == SINGLE_CALL_FILE_SHA256, (
        "the single-call template is the live path until ATLAS-104; "
        "any change to it requires a version bump, not an in-place edit"
    )


# --- the staged tickets v1.1.0 template: the correction variable (ATLAS-109) -


def tickets_v1_1_0_variables(correction: object = None) -> dict[str, object]:
    return tickets_variables() | {"correction": correction}


def test_tickets_v1_0_0_is_retained_unchanged() -> None:
    # Never edit a released template in place: v1.0.0 stays a renderable artifact
    # so any historical PlanRun pinned to it reproduces exactly.
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{TICKETS_VERSION}.md.j2").is_file()
    rendered = render_planner_prompt(tickets_variables(), version=TICKETS_VERSION)
    assert rendered.prompt_version == TICKETS_VERSION


def test_tickets_v1_1_0_declares_correction_variable() -> None:
    # v1.0.0 does not declare `correction`; v1.1.0 does (and requires it).
    with pytest.raises(UndeclaredVariableError, match="correction"):
        render_planner_prompt(
            tickets_variables() | {"correction": None}, version=TICKETS_VERSION
        )
    with pytest.raises(MissingVariableError, match="correction"):
        render_planner_prompt(tickets_variables(), version=TICKETS_V1_1_0_VERSION)


def test_tickets_v1_1_0_correction_block_renders_only_when_populated() -> None:
    heading = "Correction — your previous attempt was rejected"
    # Absent on the first attempt (correction is None): the block is empty.
    first = render_planner_prompt(
        tickets_v1_1_0_variables(correction=None),
        version=TICKETS_V1_1_0_VERSION,
    )
    assert heading not in first.text
    # Present and verbatim on a retry (correction populated).
    message = "ATLAS-109 directed correction probe — split or trim."
    retry = render_planner_prompt(
        tickets_v1_1_0_variables(correction=message),
        version=TICKETS_V1_1_0_VERSION,
    )
    assert heading in retry.text
    assert message in retry.text


def test_tickets_v1_1_0_is_additive_over_v1_0_0() -> None:
    # The v1.0.0 instructions survive verbatim into v1.1.0 (additive bump): the
    # sizing rule and the projection instruction are unchanged.
    text = render_planner_prompt(
        tickets_v1_1_0_variables(), version=TICKETS_V1_1_0_VERSION
    ).text
    assert "**Tickets for this epic only.**" in text
    assert "No ticket may have more than 7 acceptance criteria." in text


# --- the staged tickets v1.2.0 template: the key example + anti-copy (ATLAS-110)


def tickets_v1_2_0_variables(correction: object = None) -> dict[str, object]:
    return tickets_variables() | {"correction": correction}


def test_tickets_v1_1_0_is_retained_unchanged() -> None:
    # Never edit a released template in place: v1.1.0 stays renderable so any
    # historical PlanRun pinned to it (the ATLAS-109 lineage) reproduces exactly.
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{TICKETS_V1_1_0_VERSION}.md.j2").is_file()
    rendered = render_planner_prompt(
        tickets_v1_1_0_variables(), version=TICKETS_V1_1_0_VERSION
    )
    assert rendered.prompt_version == TICKETS_V1_1_0_VERSION


def test_tickets_v1_2_0_example_shows_null_key_not_a_concrete_key() -> None:
    # The root-cause fix: the JSON output-contract example shows the safe default
    # ("key": null), and no concrete ATLAS-<n> appears in the example the model
    # copied. A real-looking key in the example is exactly what failed gate 6.
    text = render_planner_prompt(
        tickets_v1_2_0_variables(), version=TICKETS_V1_2_0_VERSION
    ).text
    example = text.split("# Output contract", 1)[1]
    assert '"key": null' in example
    # The pre-fix concrete example value is gone from the example block, and no
    # ATLAS-<n> ticket key is modelled there at all.
    assert '"key": "ATLAS-24 or null"' not in text
    assert '"key": "ATLAS' not in text


def test_tickets_v1_2_0_forbids_copying_source_document_keys() -> None:
    # The anti-copy instruction names the trap: ATLAS-<n> keys in the documents
    # are not the model's to assign; a new ticket uses null regardless.
    text = render_planner_prompt(
        tickets_v1_2_0_variables(), version=TICKETS_V1_2_0_VERSION
    ).text
    assert "those are NOT keys for you to assign" in text
    assert "regardless of any `ATLAS-<n>` key shown in any" in text
    # The self-check echoes it, so instruction and check agree.
    assert "No invented or copied keys" in text


def test_tickets_v1_2_0_retains_correction_block_and_other_rules() -> None:
    # Additive over v1.1.0: the ATLAS-109 correction/retry block still works and
    # every carried instruction (projection, sizing) is intact.
    heading = "Correction — your previous attempt was rejected"
    first = render_planner_prompt(
        tickets_v1_2_0_variables(correction=None), version=TICKETS_V1_2_0_VERSION
    )
    assert heading not in first.text
    message = "ATLAS-110 carries the retry block — trim to 7."
    retry = render_planner_prompt(
        tickets_v1_2_0_variables(correction=message), version=TICKETS_V1_2_0_VERSION
    )
    assert heading in retry.text
    assert message in retry.text
    assert "**Tickets for this epic only.**" in first.text
    assert "No ticket may have more than 7 acceptance criteria." in first.text


def test_tickets_v1_2_0_renders_with_a_stable_hash() -> None:
    first = render_planner_prompt(
        tickets_v1_2_0_variables(), version=TICKETS_V1_2_0_VERSION
    )
    second = render_planner_prompt(
        tickets_v1_2_0_variables(), version=TICKETS_V1_2_0_VERSION
    )
    assert first.text == second.text
    assert first.prompt_version == TICKETS_V1_2_0_VERSION
    assert first.prompt_hash == hashlib.sha256(first.text.encode("utf-8")).hexdigest()


# --- anchor SELECTION from the index (ATLAS-111): epics v1.1.0 + tickets v1.3.0 -


def epics_v1_1_0_variables() -> dict[str, object]:
    return epics_variables() | {"valid_anchors": VALID_ANCHORS}


def tickets_v1_3_0_variables(correction: object = None) -> dict[str, object]:
    return tickets_variables() | {
        "valid_anchors": VALID_ANCHORS,
        "correction": correction,
    }


def test_epics_v1_0_0_is_retained_unchanged() -> None:
    # Prior epics version is a renderable artifact (no valid_anchors variable).
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{EPICS_VERSION}.md.j2").is_file()
    rendered = render_planner_prompt(epics_variables(), version=EPICS_VERSION)
    assert rendered.prompt_version == EPICS_VERSION


def test_epics_v1_1_0_declares_valid_anchors() -> None:
    # v1.0.0 does not declare valid_anchors; v1.1.0 does (and requires it).
    with pytest.raises(UndeclaredVariableError, match="valid_anchors"):
        render_planner_prompt(epics_v1_1_0_variables(), version=EPICS_VERSION)
    with pytest.raises(MissingVariableError, match="valid_anchors"):
        render_planner_prompt(epics_variables(), version=EPICS_V1_1_0_VERSION)


def test_epics_v1_1_0_renders_anchor_list_and_select_instruction() -> None:
    text = render_planner_prompt(
        epics_v1_1_0_variables(), version=EPICS_V1_1_0_VERSION
    ).text
    flat = " ".join(text.split())  # robust to line-wrapping of the instruction
    assert "## Valid source anchors" in text
    assert "`docs/a.md#a` — A" in text
    assert "`docs/b.md#b` — B" in text
    assert "Do NOT construct, slugify, or guess an anchor" in flat
    # The example anchor is a select-from-list placeholder, not a concrete slug
    # (the ATLAS-110 example lesson applied to anchors).
    assert "<one of the Valid source anchors above, copied verbatim>" in text
    assert "#planning-engine" not in text


def test_tickets_v1_3_0_renders_anchor_list_and_select_instruction() -> None:
    text = render_planner_prompt(
        tickets_v1_3_0_variables(), version=TICKETS_V1_3_0_VERSION
    ).text
    flat = " ".join(text.split())
    assert "## Valid source anchors" in text
    assert "`docs/a.md#a` — A" in text
    assert "Do NOT construct, slugify, or guess an anchor" in flat
    assert "<one of the Valid source anchors above, copied verbatim>" in text
    assert "#reconciler" not in text


def test_tickets_v1_3_0_carries_atlas_109_and_atlas_110_verbatim() -> None:
    # The retry-correction block (ATLAS-109) and the key instruction (ATLAS-110)
    # survive into v1.3.0 unchanged.
    heading = "Correction — your previous attempt was rejected"
    first = render_planner_prompt(
        tickets_v1_3_0_variables(correction=None), version=TICKETS_V1_3_0_VERSION
    )
    assert heading not in first.text
    # ATLAS-110: null key example + anti-copy instruction.
    assert '"key": null' in first.text
    assert "those are NOT keys for you to assign" in first.text
    # ATLAS-109: the correction block renders when populated.
    message = "ATLAS-111 carries the retry block — trim to 7."
    retry = render_planner_prompt(
        tickets_v1_3_0_variables(correction=message), version=TICKETS_V1_3_0_VERSION
    )
    assert heading in retry.text
    assert message in retry.text


def test_tickets_v1_2_0_is_retained_unchanged() -> None:
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{TICKETS_V1_2_0_VERSION}.md.j2").is_file()


# --- tickets stage emits tags/component (ATLAS-128): v1.4.0 is live ----------


def tickets_v1_4_0_variables(correction: object = None) -> dict[str, object]:
    # v1.4.0 declares the same variables as v1.3.0 (the tags/component change is
    # template prose + the auto-derived schema, no new variable).
    return tickets_v1_3_0_variables(correction)


def test_tickets_v1_4_0_instructs_tags_and_component_emission() -> None:
    text = render_planner_prompt(
        tickets_v1_4_0_variables(), version=TICKETS_V1_4_0_VERSION
    ).text
    flat = " ".join(text.split())
    # The new hard rule names both required facets and the "nothing fits"
    # emission ([]/null, never omitted) — the categorical-classification intent.
    assert "`tags` and `component` are required" in flat
    assert '"tags"' in text
    assert '"component"' in text
    assert "Emit `[]` when nothing genuinely fits" in flat
    assert "or `null` when it genuinely spans several" in flat


def test_tickets_v1_4_0_carries_v1_3_0_content_verbatim() -> None:
    # v1.4.0 is additive: the anchor-selection (v1.3.0), key (ATLAS-110), and
    # correction (ATLAS-109) content all survive unchanged.
    heading = "Correction — your previous attempt was rejected"
    first = render_planner_prompt(
        tickets_v1_4_0_variables(correction=None), version=TICKETS_V1_4_0_VERSION
    )
    flat = " ".join(first.text.split())
    assert "## Valid source anchors" in first.text
    assert "Do NOT construct, slugify, or guess an anchor" in flat
    assert '"key": null' in first.text
    assert "those are NOT keys for you to assign" in first.text
    assert heading not in first.text
    message = "ATLAS-128 carries the retry block — trim to 7."
    retry = render_planner_prompt(
        tickets_v1_4_0_variables(correction=message), version=TICKETS_V1_4_0_VERSION
    )
    assert heading in retry.text
    assert message in retry.text


def test_tickets_v1_3_0_is_retained_unchanged() -> None:
    # The superseded version stays on disk and renderable — historical PlanRuns
    # reproduce; v1.4.0 is a NEW file, never an in-place edit of v1.3.0.
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{TICKETS_V1_3_0_VERSION}.md.j2").is_file()
    rendered = render_planner_prompt(
        tickets_v1_3_0_variables(), version=TICKETS_V1_3_0_VERSION
    )
    assert rendered.prompt_version == TICKETS_V1_3_0_VERSION


def test_tickets_stage_schema_offers_tags_and_component() -> None:
    # The schema the planner is SHOWN is StageTicketsOutput.model_json_schema()
    # (wrapping ProposalTicket). If the projection omitted the facets the planner
    # would never be offered them, and the feature would be hollow (Group 3).
    from atlas.planning.staged import StageTicketsOutput

    ticket_schema = StageTicketsOutput.model_json_schema()["$defs"]["ProposalTicket"]
    assert "tags" in ticket_schema["properties"]
    assert "component" in ticket_schema["properties"]
    assert "tags" in ticket_schema["required"]
    assert "component" in ticket_schema["required"]


# --- tickets stage strengthens the ≤7 cap wording (cap emphasis): v1.5.0 live -


def tickets_v1_5_0_variables(correction: object = None) -> dict[str, object]:
    # v1.5.0 declares the same variables as v1.4.0 (the change is rule-5 prose
    # only — no new variable, same auto-derived schema).
    return tickets_v1_4_0_variables(correction)


def _tickets_rule5(text: str) -> str:
    # Rule 5 spans from its "5. **Sizing" heading to the rule-6 heading.
    return text.split("5. **Sizing", 1)[1].split("6. **No dependencies", 1)[0]


def test_tickets_v1_5_0_strengthens_acceptance_criteria_cap() -> None:
    # The intent of this change: rule 5 imports the proven _correction_message
    # remedy as first-attempt guidance — the cap, the count-before-emit step, and
    # the SPLIT/TRIM resolution. WRONG ANSWER guard: a v1.5.0 that silently
    # reverted rule 5 to the terse v1.4.0 wording fails here.
    text = render_planner_prompt(
        tickets_v1_5_0_variables(), version=TICKETS_V1_5_0_VERSION
    ).text
    rule5 = _tickets_rule5(text)
    assert "at most 7" in rule5
    assert "SPLIT" in rule5
    assert "TRIM" in rule5
    assert "count" in rule5
    # The terse v1.4.0 phrasing is gone — the emphasis replaced it, not added to.
    assert "No ticket may have more than 7 acceptance criteria." not in text


def test_tickets_v1_5_0_carries_v1_4_0_content_verbatim() -> None:
    # Additive-by-replacement: v1.5.0 differs from v1.4.0 ONLY in rule 5. Render
    # both with identical variables and assert everything around rule 5 is
    # byte-faithful — this pins the whole variable surface and every other rule
    # (anchor selection, key, tags/component, the ATLAS-109 correction block).
    variables = tickets_v1_5_0_variables()
    v1_4_0 = render_planner_prompt(variables, version=TICKETS_V1_4_0_VERSION).text
    v1_5_0 = render_planner_prompt(variables, version=TICKETS_V1_5_0_VERSION).text
    before_4, _, after_4 = v1_4_0.partition("5. **Sizing")
    before_5, _, after_5 = v1_5_0.partition("5. **Sizing")
    assert before_5 == before_4
    # Everything from rule 6 onward is identical; only the rule-5 body differs.
    assert (
        after_5.split("6. **No dependencies", 1)[1]
        == (after_4.split("6. **No dependencies", 1)[1])
    )
    # The correction block still renders only on a retry.
    heading = "Correction — your previous attempt was rejected"
    assert heading not in v1_5_0
    message = "cap-emphasis carries the retry block — trim to 7."
    retry = render_planner_prompt(
        tickets_v1_5_0_variables(correction=message), version=TICKETS_V1_5_0_VERSION
    )
    assert heading in retry.text
    assert message in retry.text


def test_tickets_v1_4_0_is_retained_unchanged() -> None:
    # The superseded version stays on disk and renderable — historical PlanRuns
    # reproduce; v1.5.0 is a NEW file, never an in-place edit of v1.4.0.
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{TICKETS_V1_4_0_VERSION}.md.j2").is_file()
    rendered = render_planner_prompt(
        tickets_v1_4_0_variables(), version=TICKETS_V1_4_0_VERSION
    )
    assert rendered.prompt_version == TICKETS_V1_4_0_VERSION


# --- re-plan seeding (ATLAS-144): epics v1.2.0 + tickets v1.6.0 --------------

SEED_EPICS_YAML = (
    "epics:\n- key: ATLAS-E1\n  title: Planning Engine\n  source_anchor: docs/a.md#a\n"
)
SEED_TICKETS_YAML = (
    "tickets:\n- key: ATLAS-1\n  title: Build plan CLI\n"
    "  source_anchor: docs/a.md#a\n  status: backlog\n"
)


def epics_v1_2_0_variables(current_backlog_yaml: object = None) -> dict[str, object]:
    return epics_v1_1_0_variables() | {"current_backlog_yaml": current_backlog_yaml}


def tickets_v1_6_0_variables(
    correction: object = None, current_backlog_yaml: object = None
) -> dict[str, object]:
    return tickets_v1_5_0_variables(correction) | {
        "current_backlog_yaml": current_backlog_yaml
    }


def test_epics_v1_1_0_is_retained_unchanged() -> None:
    # v1.1.0 stays on disk and renderable — historical PlanRuns reproduce; v1.2.0
    # is a NEW file, never an in-place edit of v1.1.0.
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{EPICS_V1_1_0_VERSION}.md.j2").is_file()
    rendered = render_planner_prompt(
        epics_v1_1_0_variables(), version=EPICS_V1_1_0_VERSION
    )
    assert rendered.prompt_version == EPICS_V1_1_0_VERSION


def test_epics_v1_2_0_declares_current_backlog_yaml() -> None:
    # v1.1.0 does not declare current_backlog_yaml; v1.2.0 does (and requires it).
    with pytest.raises(UndeclaredVariableError, match="current_backlog_yaml"):
        render_planner_prompt(epics_v1_2_0_variables(), version=EPICS_V1_1_0_VERSION)
    with pytest.raises(MissingVariableError, match="current_backlog_yaml"):
        render_planner_prompt(epics_v1_1_0_variables(), version=EPICS_V1_2_0_VERSION)


def test_epics_v1_2_0_seed_block_renders_only_when_populated() -> None:
    heading = "## Current backlog"
    first = render_planner_prompt(
        epics_v1_2_0_variables(current_backlog_yaml=None), version=EPICS_V1_2_0_VERSION
    ).text
    # The heading is always present; the seed BLOCK is not, on a first run.
    assert heading in first
    assert "<current_backlog>" not in first
    assert "This is the first planning run" in first
    seeded = render_planner_prompt(
        epics_v1_2_0_variables(current_backlog_yaml=SEED_EPICS_YAML),
        version=EPICS_V1_2_0_VERSION,
    ).text
    assert "<current_backlog>" in seeded
    assert SEED_EPICS_YAML in seeded
    assert "echoed VERBATIM" in " ".join(seeded.split())


def test_epics_v1_2_0_carries_v1_1_0_content_verbatim() -> None:
    # Additive over v1.1.0: anchor-selection content survives unchanged.
    text = render_planner_prompt(
        epics_v1_2_0_variables(), version=EPICS_V1_2_0_VERSION
    ).text
    flat = " ".join(text.split())
    assert "## Valid source anchors" in text
    assert "Do NOT construct, slugify, or guess an anchor" in flat
    assert "The environment owns identity — you never mint it." in text
    assert "<one of the Valid source anchors above, copied verbatim>" in text


def test_tickets_v1_5_0_is_retained_unchanged() -> None:
    from atlas.planning.renderer import PROMPTS_DIR

    assert (PROMPTS_DIR / f"{TICKETS_V1_5_0_VERSION}.md.j2").is_file()
    rendered = render_planner_prompt(
        tickets_v1_5_0_variables(), version=TICKETS_V1_5_0_VERSION
    )
    assert rendered.prompt_version == TICKETS_V1_5_0_VERSION


def test_tickets_v1_6_0_declares_current_backlog_yaml() -> None:
    with pytest.raises(UndeclaredVariableError, match="current_backlog_yaml"):
        render_planner_prompt(
            tickets_v1_6_0_variables(), version=TICKETS_V1_5_0_VERSION
        )
    with pytest.raises(MissingVariableError, match="current_backlog_yaml"):
        render_planner_prompt(
            tickets_v1_5_0_variables(), version=TICKETS_V1_6_0_VERSION
        )


def test_tickets_v1_6_0_seed_block_renders_only_when_populated() -> None:
    heading = "## Current backlog for this epic"
    first = render_planner_prompt(
        tickets_v1_6_0_variables(current_backlog_yaml=None),
        version=TICKETS_V1_6_0_VERSION,
    ).text
    assert heading in first
    assert "<current_backlog>" not in first
    assert "This epic has no existing tickets" in first
    seeded = render_planner_prompt(
        tickets_v1_6_0_variables(current_backlog_yaml=SEED_TICKETS_YAML),
        version=TICKETS_V1_6_0_VERSION,
    ).text
    assert "<current_backlog>" in seeded
    assert SEED_TICKETS_YAML in seeded


def test_tickets_v1_6_0_carries_v1_5_0_content_verbatim() -> None:
    # Additive over v1.5.0: the cap-emphasis rule 5, tags/component rule, and the
    # ATLAS-109 correction block all survive unchanged.
    first = render_planner_prompt(
        tickets_v1_6_0_variables(correction=None), version=TICKETS_V1_6_0_VERSION
    )
    flat = " ".join(first.text.split())
    assert "at most 7 `acceptance_criteria`, a hard cap" in first.text
    assert "`tags` and `component` are required" in flat
    assert "No ticket may have more than 7 acceptance criteria." not in first.text
    heading = "Correction — your previous attempt was rejected"
    assert heading not in first.text
    message = "ATLAS-144 carries the retry block — trim to 7."
    retry = render_planner_prompt(
        tickets_v1_6_0_variables(correction=message), version=TICKETS_V1_6_0_VERSION
    )
    assert heading in retry.text
    assert message in retry.text


# --- AC-4: the unseeded re-plan path is impossible by construction -----------


def test_selected_staged_versions_are_the_seeded_ones() -> None:
    # The generator selects the seeded versions; a regression to an unseeded
    # version would be caught here (and by the render-refusal below).
    from atlas.planning.staged import STAGE_EPICS_VERSION, STAGE_TICKETS_VERSION

    assert STAGE_EPICS_VERSION == EPICS_V1_2_0_VERSION
    assert STAGE_TICKETS_VERSION == TICKETS_V1_6_0_VERSION


def test_selected_staged_templates_refuse_to_render_without_the_seed() -> None:
    # Wrong-answer assertion (AC-4): the seeded templates the generator selects
    # DECLARE current_backlog_yaml, so the fail-closed renderer refuses to render
    # them without it — an unseeded re-plan cannot silently generate.
    from atlas.planning.staged import STAGE_EPICS_VERSION, STAGE_TICKETS_VERSION

    with pytest.raises(MissingVariableError, match="current_backlog_yaml"):
        render_planner_prompt(epics_v1_1_0_variables(), version=STAGE_EPICS_VERSION)
    with pytest.raises(MissingVariableError, match="current_backlog_yaml"):
        render_planner_prompt(tickets_v1_5_0_variables(), version=STAGE_TICKETS_VERSION)


@pytest.mark.parametrize(
    "version", [EPICS_VERSION, TICKETS_VERSION, DEPENDENCIES_VERSION]
)
def test_staged_names_cannot_repoint_current(tmp_path: Path, version: str) -> None:
    # A can't-repoint invariant, not a didn't-repoint check: the renderer's
    # CURRENT _VERSION_RE structurally rejects staged names, so the staged
    # set can never become the live release by editing CURRENT.
    directory = tmp_path / "prompts"
    directory.mkdir()
    (directory / "CURRENT").write_text(f"{version}\n", encoding="utf-8")
    with pytest.raises(CurrentReleaseError, match=version):
        render_planner_prompt({}, prompts_dir=directory)
