"""ATLAS-22: versioned planner prompt renderer.

Golden renders run against the real released v1.1.0 template; failure
taxonomies run against tmp-dir fixture templates so released artifacts
stay untouched. The fixture schema is clearly labelled: the real
proposal schema is generated by ATLAS-23's models (D2 seam).
"""

import hashlib
from pathlib import Path

import pytest

from atlas.planning import (
    CurrentReleaseError,
    FrontMatterError,
    MissingVariableError,
    RenderError,
    SourceDocument,
    UndeclaredVariableError,
    UnknownTemplateVersionError,
    current_release,
    render_planner_prompt,
)

FIXTURE_SCHEMA = '{"$comment": "FIXTURE SCHEMA - not the proposal schema (ATLAS-23)"}'

DECLARED_VARIABLES = (
    "product_key",
    "documents",
    "current_backlog_yaml",
    "frozen_ticket_keys",
    "next_key_hint",
    "proposal_json_schema",
)

FIXTURE_TEMPLATE = """\
---
prompt_version: "planner-v9.9.9"
template_engine: "jinja2"
template_variables:
  - greeting
---
Hello {{ greeting }}
"""


def golden_variables() -> dict[str, object]:
    return {
        "product_key": "ATLAS",
        "documents": [
            SourceDocument(path="docs/a.md", sha="sha-aaa", content="# A\n"),
            SourceDocument(path="docs/b.md", sha="sha-bbb", content="# B\n"),
        ],
        "current_backlog_yaml": "tickets: []\n",
        "frozen_ticket_keys": ["ATLAS-1", "ATLAS-2"],
        "next_key_hint": "ATLAS-101",
        "proposal_json_schema": FIXTURE_SCHEMA,
    }


def fixture_prompts_dir(tmp_path: Path, current: str | None) -> Path:
    directory = tmp_path / "prompts"
    directory.mkdir()
    (directory / "planner-v9.9.9.md.j2").write_text(FIXTURE_TEMPLATE, encoding="utf-8")
    if current is not None:
        (directory / "CURRENT").write_text(current, encoding="utf-8")
    return directory


# --- golden renders against the released v1.1.0 ------------------------------


def test_default_release_is_v1_1_0() -> None:
    assert current_release() == "planner-v1.1.0"


def test_golden_render_is_byte_identical_and_positioned() -> None:
    first = render_planner_prompt(golden_variables())
    second = render_planner_prompt(golden_variables())
    assert first.text == second.text
    assert first.prompt_version == "planner-v1.1.0"

    text = first.text
    assert '<document path="docs/a.md" sha="sha-aaa">' in text
    assert '<document path="docs/b.md" sha="sha-bbb">' in text
    assert "<current_backlog>\ntickets: []" in text
    assert "- ATLAS-1\n- ATLAS-2" in text
    assert FIXTURE_SCHEMA in text
    # v1.1.0 marker: rule 4 carries the definition_of_done requirement.
    assert "definition_of_done" in text


def test_first_run_branch_renders_alternate_sections() -> None:
    variables = golden_variables() | {
        "current_backlog_yaml": None,
        "frozen_ticket_keys": [],
    }
    text = render_planner_prompt(variables).text
    assert "There is no existing backlog" in text
    assert "No tickets are currently frozen." in text
    assert "<current_backlog>" not in text


def test_prompt_hash_is_sha256_of_text() -> None:
    rendered = render_planner_prompt(golden_variables())
    expected = hashlib.sha256(rendered.text.encode("utf-8")).hexdigest()
    assert rendered.prompt_hash == expected


# --- variable validation (fail closed, both directions) ----------------------


@pytest.mark.parametrize("name", DECLARED_VARIABLES)
def test_each_missing_declared_variable_fails_before_render(name: str) -> None:
    variables = golden_variables()
    del variables[name]
    with pytest.raises(MissingVariableError, match=name):
        render_planner_prompt(variables)


def test_undeclared_extra_variable_fails(tmp_path: Path) -> None:
    with pytest.raises(UndeclaredVariableError, match="surprise"):
        render_planner_prompt(golden_variables() | {"surprise": 1})


def test_strict_undefined_names_the_variable(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current=None)
    template = FIXTURE_TEMPLATE.replace(
        "Hello {{ greeting }}", "Hello {{ greeting }} {{ missing_thing }}"
    )
    (directory / "planner-v9.9.9.md.j2").write_text(template, encoding="utf-8")
    with pytest.raises(RenderError, match="missing_thing"):
        render_planner_prompt(
            {"greeting": "world"},
            version="planner-v9.9.9",
            prompts_dir=directory,
        )


# --- CURRENT pointer (the gap mechanism) -------------------------------------


def test_missing_current_pointer_fails_typed(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current=None)
    with pytest.raises(CurrentReleaseError, match="missing"):
        render_planner_prompt({"greeting": "x"}, prompts_dir=directory)


def test_malformed_current_pointer_fails_typed(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current="banana\n")
    with pytest.raises(CurrentReleaseError, match="banana"):
        render_planner_prompt({"greeting": "x"}, prompts_dir=directory)


def test_current_pointing_at_absent_template_fails(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current="planner-v0.0.1\n")
    with pytest.raises(UnknownTemplateVersionError, match=r"planner-v0\.0\.1"):
        render_planner_prompt({"greeting": "x"}, prompts_dir=directory)


def test_explicit_version_bypasses_current(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current=None)  # no CURRENT
    rendered = render_planner_prompt(
        {"greeting": "world"}, version="planner-v9.9.9", prompts_dir=directory
    )
    assert rendered.text == "Hello world"
    assert rendered.prompt_version == "planner-v9.9.9"


# --- front-matter validation --------------------------------------------------


def write_template(directory: Path, name: str, content: str) -> None:
    (directory / name).write_text(content, encoding="utf-8")


def test_no_front_matter_fails(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current=None)
    write_template(directory, "planner-v9.9.8.md.j2", "Just a body, no header\n")
    with pytest.raises(FrontMatterError, match="front matter"):
        render_planner_prompt(
            {"greeting": "x"}, version="planner-v9.9.8", prompts_dir=directory
        )


def test_unknown_engine_fails(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current=None)
    bad = FIXTURE_TEMPLATE.replace('"jinja2"', '"handlebars"').replace(
        "v9.9.9", "v9.9.8"
    )
    write_template(directory, "planner-v9.9.8.md.j2", bad)
    with pytest.raises(FrontMatterError, match="handlebars"):
        render_planner_prompt(
            {"greeting": "x"}, version="planner-v9.9.8", prompts_dir=directory
        )


def test_missing_template_variables_list_fails(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current=None)
    bad = FIXTURE_TEMPLATE.replace("template_variables:\n  - greeting\n", "").replace(
        "v9.9.9", "v9.9.8"
    )
    write_template(directory, "planner-v9.9.8.md.j2", bad)
    with pytest.raises(FrontMatterError, match="template_variables"):
        render_planner_prompt(
            {"greeting": "x"}, version="planner-v9.9.8", prompts_dir=directory
        )


def test_version_filename_mismatch_fails(tmp_path: Path) -> None:
    directory = fixture_prompts_dir(tmp_path, current=None)
    # File named 9.9.8 but front matter still declares 9.9.9.
    write_template(directory, "planner-v9.9.8.md.j2", FIXTURE_TEMPLATE)
    with pytest.raises(FrontMatterError, match="must agree"):
        render_planner_prompt(
            {"greeting": "x"}, version="planner-v9.9.8", prompts_dir=directory
        )
