"""Planning engine: plan/apply loop, reconciler, validation gates."""

from atlas.core.anchors import (
    AnchorIndex,
    IngestionError,
    MalformedAnchorError,
    ResolvedAnchor,
    SourceDocument,
    UnknownAnchorError,
    UnknownDocumentError,
    slugify,
)
from atlas.planning.gates import GateFailure, run_gates
from atlas.planning.ingestion import (
    DirtyInputError,
    collect_inbox_documents,
    collect_input_documents,
)
from atlas.planning.proposal import (
    Proposal,
    ProposalDependency,
    ProposalEpic,
    ProposalError,
    ProposalParseError,
    ProposalReferenceError,
    ProposalTicket,
    ProposalValidationError,
    extract_json_object,
    parse_proposal,
)
from atlas.planning.reconciler import (
    DEFAULT_SIMILARITY_THRESHOLD,
    FROZEN_STATUSES,
    Backlog,
    DiffEntry,
    PlanDiff,
    reconcile,
    similarity,
)
from atlas.planning.renderer import (
    CurrentReleaseError,
    FrontMatterError,
    MissingVariableError,
    RenderedPrompt,
    RendererError,
    RenderError,
    UndeclaredVariableError,
    UnknownTemplateVersionError,
    current_release,
    render_planner_prompt,
)

__all__ = [
    "DEFAULT_SIMILARITY_THRESHOLD",
    "FROZEN_STATUSES",
    "AnchorIndex",
    "Backlog",
    "CurrentReleaseError",
    "DiffEntry",
    "DirtyInputError",
    "FrontMatterError",
    "GateFailure",
    "IngestionError",
    "MalformedAnchorError",
    "MissingVariableError",
    "PlanDiff",
    "Proposal",
    "ProposalDependency",
    "ProposalEpic",
    "ProposalError",
    "ProposalParseError",
    "ProposalReferenceError",
    "ProposalTicket",
    "ProposalValidationError",
    "RenderError",
    "RenderedPrompt",
    "RendererError",
    "ResolvedAnchor",
    "SourceDocument",
    "UndeclaredVariableError",
    "UnknownAnchorError",
    "UnknownDocumentError",
    "UnknownTemplateVersionError",
    "collect_inbox_documents",
    "collect_input_documents",
    "current_release",
    "extract_json_object",
    "parse_proposal",
    "reconcile",
    "render_planner_prompt",
    "run_gates",
    "similarity",
    "slugify",
]
