"""knowledge core baseline

Revision ID: 0001
Revises:
Create Date: 2026-06-12 12:29:06.601841
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from atlas.storage.tables import JSONB, UTCDateTime

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("vision", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("goals", JSONB, server_default=sa.text("'[]'"), nullable=False),
        sa.Column("non_goals", JSONB, server_default=sa.text("'[]'"), nullable=False),
        sa.Column("constraints", JSONB, server_default=sa.text("'[]'"), nullable=False),
        sa.Column("created_by_type", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("archived_at", UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "architecture_decision_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "consequences", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "alternatives_considered",
            JSONB,
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("supersedes_adr_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_type", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_adr_id"],
            ["architecture_decision_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "number"),
    )
    op.create_table(
        "epics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "priority", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("risk_level", sa.Text(), nullable=False),
        sa.Column("created_by_type", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("completed_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("solution", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column(
            "confidence",
            sa.Numeric(precision=4, scale=3, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "related_ticket_ids", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "related_adr_ids", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("tags", JSONB, server_default=sa.text("'[]'"), nullable=False),
        sa.Column("created_by_type", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="lessons_confidence_bounds"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plan_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "input_doc_shas", JSONB, server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("model_provider", sa.Text(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column(
            "similarity_threshold",
            sa.Numeric(precision=4, scale=3, asdecimal=False),
            nullable=False,
        ),
        sa.Column("raw_output_hash", sa.Text(), nullable=False),
        sa.Column(
            "diff_summary", JSONB, server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.Text(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("applied_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("epic_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("ticket_type", sa.Text(), nullable=False),
        sa.Column("risk_level", sa.Text(), nullable=False),
        sa.Column(
            "priority", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "relevant_docs", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "acceptance_criteria", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("non_goals", JSONB, server_default=sa.text("'[]'"), nullable=False),
        sa.Column(
            "implementation_notes",
            JSONB,
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "test_requirements", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "documentation_requirements",
            JSONB,
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "definition_of_done", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("estimated_effort", sa.Integer(), nullable=True),
        sa.Column("external_linear_id", sa.Text(), nullable=True),
        sa.Column("external_github_issue_id", sa.Text(), nullable=True),
        sa.Column("created_by_type", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("completed_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["epic_id"],
            ["epics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("input_context_pack_id", sa.Uuid(), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "cost_estimate_usd",
            sa.Numeric(precision=12, scale=4, asdecimal=False),
            nullable=True,
        ),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("started_at", UTCDateTime(), nullable=True),
        sa.Column("completed_at", UTCDateTime(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "context_packs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("constraints", JSONB, server_default=sa.text("'[]'"), nullable=False),
        sa.Column(
            "relevant_docs", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "relevant_adrs", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "related_tickets", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "historical_lessons", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "acceptance_criteria", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("risks", JSONB, server_default=sa.text("'[]'"), nullable=False),
        sa.Column(
            "test_commands", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "definition_of_done", JSONB, server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("rendered_markdown", sa.Text(), nullable=False),
        sa.Column(
            "input_doc_shas", JSONB, server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("token_estimate", sa.Integer(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.Text(), nullable=True),
        sa.Column("external_run_id", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.Text(), nullable=True),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("raw_payload", JSONB, server_default=sa.text("'{}'"), nullable=False),
        sa.Column("created_by_type", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket_dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_ticket_id", sa.Uuid(), nullable=False),
        sa.Column("target_entity_type", sa.Text(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column("dependency_type", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by_type", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_dependencies")
    op.drop_table("evidence")
    op.drop_table("context_packs")
    op.drop_table("agent_runs")
    op.drop_table("tickets")
    op.drop_table("plan_runs")
    op.drop_table("lessons")
    op.drop_table("epics")
    op.drop_table("architecture_decision_records")
    op.drop_table("products")
    # ### end Alembic commands ###
