// This file is generated by atlas.tools.operator_ui_openapi.
// Do not edit it by hand.

export const atlasOpenApiEnums = {
  "ActorType": [
    "human",
    "agent",
    "system"
  ],
  "DependencyType": [
    "depends_on",
    "relates_to",
    "implements",
    "supersedes"
  ],
  "EntityStatus": [
    "draft",
    "active",
    "archived",
    "deprecated"
  ],
  "EpicStatus": [
    "backlog",
    "planned",
    "in_progress",
    "done",
    "archived"
  ],
  "EvidenceStatus": [
    "pending",
    "passed",
    "failed",
    "warning",
    "not_applicable"
  ],
  "EvidenceType": [
    "test_result",
    "build_result",
    "lint_result",
    "coverage_report",
    "screenshot",
    "pr_review",
    "deployment_result",
    "documentation_update",
    "manual_approval",
    "pr_merged"
  ],
  "LessonCategory": [
    "success_pattern",
    "failure_pattern",
    "architecture",
    "testing",
    "delivery",
    "product",
    "research",
    "tech_debt"
  ],
  "NotReadyCode": [
    "wrong_status",
    "dependency_not_done",
    "adr_not_accepted",
    "no_acceptance_criteria",
    "dangling_target"
  ],
  "RiskLevel": [
    "low",
    "medium",
    "high",
    "critical"
  ],
  "TicketStatus": [
    "backlog",
    "planned",
    "blocked",
    "ready_for_agent",
    "in_progress",
    "pr_open",
    "review_required",
    "changes_requested",
    "done",
    "rejected",
    "needs_human_decision"
  ],
  "TicketType": [
    "feature",
    "bug",
    "tech_debt",
    "spike",
    "documentation",
    "infrastructure",
    "research"
  ],
  "VerificationCheckType": [
    "acceptance_criteria",
    "tests",
    "lint",
    "documentation",
    "scope",
    "security",
    "human_approval"
  ]
} as const

export type AtlasOpenApiEnumName = keyof typeof atlasOpenApiEnums
