// This file is generated by atlas.tools.operator_ui_openapi.
// Do not edit it by hand.

export const atlasOpenApiEnums = {
  "AcceptanceConfirmationValidationCode": [
    "session_unknown",
    "criteria_fingerprint_mismatch",
    "manual_approval_required",
    "missing_criterion_index",
    "duplicate_criterion_index",
    "unknown_criterion_index",
    "extra_criterion_index"
  ],
  "AcceptanceSessionBlockingReason": [
    "pr_unknown",
    "pr_merged",
    "pr_closed",
    "pr_draft",
    "pr_fork_head",
    "pr_non_main",
    "integration_behind",
    "integration_diverged",
    "integration_conflicted",
    "integration_indeterminate",
    "external_state_indeterminate",
    "close_set_empty",
    "unknown_ticket",
    "ticket_not_review_required",
    "active_session_exists",
    "idempotency_key_reused",
    "repository_mismatch",
    "pr_number_mismatch",
    "head_ref_mismatch",
    "head_sha_mismatch",
    "head_repository_mismatch",
    "base_ref_mismatch",
    "base_sha_mismatch",
    "base_repository_mismatch",
    "close_set_mismatch",
    "eligibility_mismatch",
    "integration_status_mismatch",
    "criteria_mismatch",
    "session_stale",
    "evidence_not_ready",
    "confirmations_not_ready",
    "verification_not_passed",
    "session_unknown",
    "session_not_verifiable",
    "verification_already_completed",
    "verification_pending",
    "verification_failed",
    "verification_warning",
    "verification_not_applicable",
    "verification_malformed",
    "verification_close_set_mismatch",
    "verified_head_invalid",
    "verified_head_mismatch",
    "stored_history_invalid",
    "readiness_persistence_failed",
    "external_read_timeout",
    "external_response_malformed",
    "external_read_failed"
  ],
  "AcceptanceSessionLifecycle": [
    "preflight_passed",
    "evidence_ready",
    "confirmations_ready",
    "verification_passed",
    "merge_ready",
    "stale",
    "blocked",
    "failed"
  ],
  "AcceptanceSessionStep": [
    "preflight",
    "evidence",
    "confirmations",
    "verification",
    "readiness"
  ],
  "AcceptanceSessionStepState": [
    "pending",
    "complete",
    "blocked",
    "failed"
  ],
  "ActorType": [
    "human",
    "agent",
    "system"
  ],
  "AdmissionDecisionType": [
    "admit",
    "hold"
  ],
  "AdmissionHoldCode": [
    "policy_paused",
    "policy_draining",
    "snapshot_policy_mismatch",
    "snapshot_incomplete",
    "working_budget",
    "integration_budget",
    "review_budget",
    "changes_requested_reserve",
    "risk_lane",
    "component_lane",
    "protected_lane",
    "protected_lane_declaration",
    "missing_external_linear_id",
    "single_write_limit"
  ],
  "AdmissionSyncReason": [
    "lease_unavailable",
    "ci_handoff_fence_present",
    "product_ambiguous",
    "policy_unavailable",
    "snapshot_incomplete",
    "no_candidate",
    "policy_or_capacity_hold",
    "over_capacity",
    "revalidation_failed",
    "revalidation_mismatch",
    "policy_changed",
    "protected_lane_registry_unavailable",
    "protected_lane_registry_changed",
    "protected_lane_state_changed",
    "candidate_moved",
    "lease_lost",
    "write_confirmed",
    "write_indeterminate",
    "indeterminate_still_unresolved",
    "indeterminate_reconciled_admitted",
    "indeterminate_reconciled_no_write",
    "indeterminate_reconciled_moved"
  ],
  "CIHandoffClassification": [
    "passed",
    "implementation_failure",
    "pending",
    "missing",
    "infrastructure",
    "stale",
    "malformed",
    "indeterminate"
  ],
  "CIHandoffDecision": [
    "hold",
    "review_required",
    "changes_requested"
  ],
  "CIHandoffReason": [
    "complete_required_checks_passed",
    "complete_implementation_failure",
    "required_checks_pending",
    "required_checks_missing",
    "infrastructure_evidence",
    "stale_evidence",
    "malformed_evidence",
    "contradictory_evidence",
    "indeterminate_evidence",
    "no_ci_required_checks",
    "lease_unavailable",
    "lease_lost",
    "policy_unavailable",
    "snapshot_incomplete",
    "ticket_not_ci_pending",
    "ticket_identity_mismatch",
    "linear_issue_missing",
    "linear_state_mismatch",
    "pr_identity_malformed",
    "pr_head_moved",
    "github_infrastructure",
    "board_revalidation_failed",
    "board_state_moved",
    "policy_changed",
    "snapshot_changed",
    "evidence_changed",
    "concurrent_write_fence",
    "fence_still_unresolved",
    "fence_reconciled_target",
    "fence_reconciled_source",
    "fence_reconciled_moved",
    "write_confirmed",
    "write_indeterminate"
  ],
  "DeliveryAdmissionMode": [
    "running",
    "paused",
    "draining"
  ],
  "DeliveryAdmissionPolicyConflictCode": [
    "stale_revision",
    "idempotency_key_reused",
    "in_progress"
  ],
  "DeliveryControlExactBaseStatus": [
    "exact_branch",
    "rebase_required",
    "stale",
    "indeterminate"
  ],
  "DeliveryControlProjectionReason": [
    "successful_board_unavailable",
    "newer_board_refresh_unsuccessful",
    "evidence_identity_missing",
    "protected_lane_classification_invalid",
    "ci_reconciliation_unavailable",
    "ci_handoff_write_indeterminate",
    "validation_plan_provenance_unavailable",
    "exact_base_assessment_unavailable",
    "integration_identity_mismatch",
    "acceptance_assessment_stale",
    "integration_behind",
    "integration_diverged",
    "integration_conflicted",
    "integration_indeterminate"
  ],
  "DeliveryControlSnapshotStatus": [
    "coherent",
    "stale",
    "indeterminate"
  ],
  "DeliveryControlValidationPlanStatus": [
    "available",
    "stale",
    "indeterminate"
  ],
  "DependencyType": [
    "depends_on",
    "relates_to",
    "implements",
    "supersedes"
  ],
  "EntityStatus": [
    "draft",
    "active",
    "archived",
    "deprecated"
  ],
  "EpicStatus": [
    "backlog",
    "planned",
    "in_progress",
    "done",
    "archived"
  ],
  "EvidenceStatus": [
    "pending",
    "passed",
    "failed",
    "warning",
    "not_applicable"
  ],
  "EvidenceType": [
    "test_result",
    "build_result",
    "lint_result",
    "coverage_report",
    "screenshot",
    "pr_review",
    "deployment_result",
    "documentation_update",
    "manual_approval",
    "pr_merged"
  ],
  "LessonCategory": [
    "success_pattern",
    "failure_pattern",
    "architecture",
    "testing",
    "delivery",
    "product",
    "research",
    "tech_debt"
  ],
  "NotReadyCode": [
    "wrong_status",
    "dependency_not_done",
    "adr_not_accepted",
    "no_acceptance_criteria",
    "dangling_target"
  ],
  "OccupancyDimension": [
    "working",
    "integration",
    "review",
    "risk_lane",
    "component_lane",
    "protected_lane"
  ],
  "OperatorActionConflictCode": [
    "idempotency_key_reused",
    "in_progress",
    "stale_state"
  ],
  "OperatorActionFailureCode": [
    "command_failed",
    "receipt_commit_failed",
    "storage_failed"
  ],
  "OperatorActionOutcome": [
    "succeeded",
    "refused",
    "failed",
    "conflict"
  ],
  "OperatorActionResultCode": [
    "action_succeeded",
    "action_refused",
    "stale_state",
    "action_failed",
    "external_timeout",
    "evidence_transport_failed",
    "evidence_authentication_failed",
    "evidence_rate_limit_failed",
    "evidence_malformed_source",
    "action_conflict"
  ],
  "PmSyncReceiptResult": [
    "success_definition_changed",
    "success_status_only",
    "success_zero_action",
    "partial",
    "malformed_pull",
    "cancelled",
    "failed"
  ],
  "RiskLevel": [
    "low",
    "medium",
    "high",
    "critical"
  ],
  "TicketStatus": [
    "backlog",
    "planned",
    "blocked",
    "ready_for_agent",
    "in_progress",
    "pr_open",
    "ci_pending",
    "review_required",
    "changes_requested",
    "done",
    "rejected",
    "needs_human_decision"
  ],
  "TicketType": [
    "feature",
    "bug",
    "tech_debt",
    "spike",
    "documentation",
    "infrastructure",
    "research"
  ],
  "VerificationCheckType": [
    "acceptance_criteria",
    "tests",
    "lint",
    "documentation",
    "scope",
    "security",
    "human_approval"
  ]
} as const

export type AtlasOpenApiEnumName = keyof typeof atlasOpenApiEnums
