/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dependencies/critical-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency Critical Path Route */
        get: operations["dependency_critical_path_route_api_v1_dependencies_critical_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dependencies/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency Graph Route */
        get: operations["dependency_graph_route_api_v1_dependencies_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/epics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Epics */
        get: operations["list_epics_api_v1_epics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lessons */
        get: operations["list_lessons_api_v1_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote Lesson */
        post: operations["promote_lesson_api_v1_lessons__lesson_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Lesson */
        post: operations["reject_lesson_api_v1_lessons__lesson_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Operator Session */
        get: operations["read_operator_session_api_v1_session_get"];
        put?: never;
        /** Create Operator Session */
        post: operations["create_operator_session_api_v1_session_post"];
        /** Revoke Operator Session */
        delete: operations["revoke_operator_session_api_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read System Status */
        get: operations["read_system_status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_v1_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Detail */
        get: operations["ticket_detail_api_v1_tickets__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{key}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Dependency State */
        get: operations["ticket_dependency_state_api_v1_tickets__key__dependencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{key}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Evidence Records */
        get: operations["ticket_evidence_records_api_v1_tickets__key__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Count */
        get: operations["ticket_count_api_v1_tickets_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorType
         * @description Who or what created a record (data-model §2.2, attribution §1.5).
         * @enum {string}
         */
        ActorType: "human" | "agent" | "system";
        /**
         * CriticalPathStepSchema
         * @description One ticket on the graph-wide critical path.
         */
        CriticalPathStepSchema: {
            /** Cumulative Effort */
            cumulative_effort: number;
            /** Effort */
            effort: number;
            /** Key */
            key: string;
        };
        /**
         * DependencyBlockerSchema
         * @description One dependency target currently blocking a ticket.
         */
        DependencyBlockerSchema: {
            code: components["schemas"]["NotReadyCode"];
            /** Key */
            key: string;
        };
        /**
         * DependencyCriticalPathResponse
         * @description Graph-wide critical path in execution order.
         */
        DependencyCriticalPathResponse: {
            /** Keys */
            keys: string[];
            /** Steps */
            steps: components["schemas"]["CriticalPathStepSchema"][];
            /** Total Effort */
            total_effort: number;
        };
        /**
         * DependencyGraphEdgeSchema
         * @description One depends_on edge in the projected dependency graph.
         */
        DependencyGraphEdgeSchema: {
            dependency_type: components["schemas"]["DependencyType"];
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * DependencyGraphNodeSchema
         * @description One node in the projected dependency graph.
         */
        DependencyGraphNodeSchema: {
            /** Key */
            key: string;
            /** Node Type */
            node_type: string;
            /** Status */
            status: string;
        };
        /**
         * DependencyGraphResponse
         * @description Whole projected dependency graph in deterministic order.
         */
        DependencyGraphResponse: {
            /** Edges */
            edges: components["schemas"]["DependencyGraphEdgeSchema"][];
            /** Nodes */
            nodes: components["schemas"]["DependencyGraphNodeSchema"][];
        };
        /**
         * DependencyType
         * @enum {string}
         */
        DependencyType: "depends_on" | "relates_to" | "implements" | "supersedes";
        /**
         * EntityStatus
         * @description Generic lifecycle status for knowledge entities (data-model §2.3).
         * @enum {string}
         */
        EntityStatus: "draft" | "active" | "archived" | "deprecated";
        /**
         * EpicItemSchema
         * @description One stored epic exposed to the operator.
         */
        EpicItemSchema: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Id */
            created_by_id: string;
            created_by_type: components["schemas"]["ActorType"];
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Objective */
            objective: string;
            /** Priority */
            priority: number;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            risk_level: components["schemas"]["RiskLevel"];
            /** Source Anchor */
            source_anchor: string;
            status: components["schemas"]["EpicStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EpicsResponse
         * @description Stored epics for the operator.
         */
        EpicsResponse: {
            /** Epics */
            epics: components["schemas"]["EpicItemSchema"][];
        };
        /**
         * EpicStatus
         * @description Lifecycle of an epic (data-model §3.3).
         * @enum {string}
         */
        EpicStatus: "backlog" | "planned" | "in_progress" | "done" | "archived";
        /**
         * EvidenceStatus
         * @description Outcome of an evidence record or verification check (data-model §2.5).
         * @enum {string}
         */
        EvidenceStatus: "pending" | "passed" | "failed" | "warning" | "not_applicable";
        /**
         * EvidenceType
         * @description What an evidence record attests (data-model §3.7).
         * @enum {string}
         */
        EvidenceType: "test_result" | "build_result" | "lint_result" | "coverage_report" | "screenshot" | "pr_review" | "deployment_result" | "documentation_update" | "manual_approval" | "pr_merged";
        /**
         * GraphValidationErrorResponse
         * @description A dependency projection refused because stored graph data is invalid.
         */
        GraphValidationErrorResponse: {
            /** Detail */
            detail: string;
            /** Violations */
            violations: components["schemas"]["GraphValidationViolationSchema"][];
        };
        /**
         * GraphValidationViolationSchema
         * @description One typed dependency-graph integrity violation.
         */
        GraphValidationViolationSchema: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LessonCategory
         * @description What kind of organisational learning a lesson records (data-model
         *     §3.6).
         * @enum {string}
         */
        LessonCategory: "success_pattern" | "failure_pattern" | "architecture" | "testing" | "delivery" | "product" | "research" | "tech_debt";
        /**
         * LessonDispositionConflictResponse
         * @description Typed command conflict with the safe current lesson when available.
         */
        LessonDispositionConflictResponse: {
            /** Detail */
            detail: string;
            lesson: components["schemas"]["LessonItemSchema"] | null;
        };
        /**
         * LessonDispositionErrorResponse
         * @description Non-secret command error without internal failure material.
         */
        LessonDispositionErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * LessonDispositionResponse
         * @description Updated safe lesson projection and its durable action receipt.
         */
        LessonDispositionResponse: {
            lesson: components["schemas"]["LessonItemSchema"];
            receipt: components["schemas"]["OperatorActionReceiptSchema"];
        };
        /**
         * LessonItemSchema
         * @description One stored lesson exposed as a read-only projection.
         */
        LessonItemSchema: {
            category: components["schemas"]["LessonCategory"];
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Id */
            created_by_id: string;
            created_by_type: components["schemas"]["ActorType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Outcome */
            outcome: string;
            /** Problem */
            problem: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Related Adr Ids */
            related_adr_ids: string[];
            /** Related Ticket Ids */
            related_ticket_ids: string[];
            /** Solution */
            solution: string;
            /**
             * Source Ticket Id
             * Format: uuid
             */
            source_ticket_id: string;
            status: components["schemas"]["EntityStatus"];
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LessonsResponse
         * @description Stored lessons for the operator.
         */
        LessonsResponse: {
            /** Lessons */
            lessons: components["schemas"]["LessonItemSchema"][];
        };
        /**
         * NotReadyCode
         * @description Why a ticket is not ready — one code per failing readiness condition,
         *     so a caller can branch on the machine code and show the message.
         * @enum {string}
         */
        NotReadyCode: "wrong_status" | "dependency_not_done" | "adr_not_accepted" | "no_acceptance_criteria" | "dangling_target";
        /**
         * NotReadyReasonSchema
         * @description One readiness condition that is not satisfied.
         */
        NotReadyReasonSchema: {
            code: components["schemas"]["NotReadyCode"];
            /** Message */
            message: string;
            /** Status */
            status: string | null;
            /** Target */
            target: string | null;
        };
        /**
         * OperatorActionActorSchema
         * @description Server-owned actor recorded by an operator-action receipt.
         */
        OperatorActionActorSchema: {
            /**
             * Id
             * @constant
             */
            id: "operator";
            /**
             * Type
             * @constant
             */
            type: "human";
        };
        /**
         * OperatorActionOutcome
         * @description Terminal outcome stored on an operator action receipt.
         * @enum {string}
         */
        OperatorActionOutcome: "succeeded" | "refused" | "failed" | "conflict";
        /**
         * OperatorActionReceiptSchema
         * @description Safe, bounded operator-action receipt returned by a command.
         */
        OperatorActionReceiptSchema: {
            /**
             * Action
             * @enum {string}
             */
            action: "lesson.promote" | "lesson.reject";
            actor: components["schemas"]["OperatorActionActorSchema"];
            after_status: components["schemas"]["EntityStatus"] | null;
            before_status: components["schemas"]["EntityStatus"] | null;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /**
             * Correlation Id
             * Format: uuid
             */
            correlation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Idempotency Key Identity */
            idempotency_key_identity: string;
            outcome: components["schemas"]["OperatorActionOutcome"];
            /**
             * Receipt Id
             * Format: uuid
             */
            receipt_id: string;
            /** Request Fingerprint */
            request_fingerprint: string;
            result_code: components["schemas"]["OperatorActionResultCode"];
            /** Result Metadata */
            result_metadata: {
                [key: string]: boolean | number;
            };
            target: components["schemas"]["OperatorActionTargetSchema"];
        };
        /**
         * OperatorActionResultCode
         * @description Server-controlled terminal result vocabulary for operator commands.
         * @enum {string}
         */
        OperatorActionResultCode: "action_succeeded" | "action_refused" | "stale_state" | "action_failed" | "evidence_transport_failed" | "evidence_authentication_failed" | "evidence_rate_limit_failed" | "evidence_malformed_source" | "action_conflict";
        /**
         * OperatorActionTargetSchema
         * @description Bounded lesson target recorded by an operator-action receipt.
         */
        OperatorActionTargetSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Type
             * @constant
             */
            type: "lesson";
        };
        /**
         * PromoteLessonRequest
         * @description Exact command payload for promoting one DRAFT lesson.
         */
        PromoteLessonRequest: {
            /** Confidence */
            confidence: number;
        };
        /**
         * RejectLessonRequest
         * @description Exact empty command payload for rejecting one DRAFT lesson.
         */
        RejectLessonRequest: Record<string, never>;
        /**
         * ReviewCheckSchema
         * @description One persisted verification outcome in a review item.
         */
        ReviewCheckSchema: {
            check_type: components["schemas"]["VerificationCheckType"];
            status: components["schemas"]["EvidenceStatus"];
        };
        /**
         * ReviewQueueItemSchema
         * @description One ticket awaiting operator review.
         */
        ReviewQueueItemSchema: {
            /** Checks */
            checks: components["schemas"]["ReviewCheckSchema"][];
            /** Has Pr Merged Evidence */
            has_pr_merged_evidence: boolean;
            /** Has System Evidence */
            has_system_evidence: boolean;
            /** Key */
            key: string;
            status: components["schemas"]["TicketStatus"];
            ticket_type: components["schemas"]["TicketType"];
            /** Title */
            title: string;
            verdict: components["schemas"]["EvidenceStatus"];
        };
        /**
         * ReviewQueueResponse
         * @description Operator review queue.
         */
        ReviewQueueResponse: {
            /** Reviews */
            reviews: components["schemas"]["ReviewQueueItemSchema"][];
        };
        /**
         * RiskLevel
         * @description Risk classification shared by epics and tickets (data-model §2.4).
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high" | "critical";
        /**
         * SessionLoginRequest
         * @description Bootstrap-token login request for the single local operator.
         * @example {
         *       "token": "<ATLAS_OPERATOR_TOKEN>"
         *     }
         */
        SessionLoginRequest: {
            /** Token */
            token: string;
        };
        /**
         * SessionLoginResponse
         * @description Successful operator login state plus one in-memory CSRF value.
         */
        SessionLoginResponse: {
            /**
             * Authenticated
             * @constant
             */
            authenticated: true;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * SessionStateResponse
         * @description Current browser session state without credential material.
         */
        SessionStateResponse: {
            /** Authenticated */
            authenticated: boolean;
            /** Expires At */
            expires_at: string | null;
        };
        /**
         * SystemStatusResponse
         * @description Singleton operator-facing Atlas instance status.
         */
        SystemStatusResponse: {
            /** Evidence Count */
            evidence_count: number;
            /** Last Evidence Pull At */
            last_evidence_pull_at: string | null;
            /** Last Linear Sync At */
            last_linear_sync_at: string | null;
            /** Package Version */
            package_version: string;
            /** Schema Revision */
            schema_revision: string | null;
            /** Ticket Count */
            ticket_count: number;
        };
        /**
         * TicketBoardItemSchema
         * @description One lean ticket card on the operator board.
         */
        TicketBoardItemSchema: {
            /** Epic Key */
            epic_key: string | null;
            /** Key */
            key: string;
            /** Priority */
            priority: number;
            risk_level: components["schemas"]["RiskLevel"];
            status: components["schemas"]["TicketStatus"];
            ticket_type: components["schemas"]["TicketType"];
            /** Title */
            title: string;
        };
        /**
         * TicketBoardResponse
         * @description Lean tickets displayed on the operator board.
         */
        TicketBoardResponse: {
            /** Tickets */
            tickets: components["schemas"]["TicketBoardItemSchema"][];
        };
        /**
         * TicketCountResponse
         * @description Number of tickets in the Atlas store.
         */
        TicketCountResponse: {
            /** Count */
            count: number;
        };
        /**
         * TicketDependenciesResponse
         * @description Dependency readiness and reverse dependency state for one ticket.
         */
        TicketDependenciesResponse: {
            /** Blocked By */
            blocked_by: string[];
            /** Blockers */
            blockers: components["schemas"]["DependencyBlockerSchema"][];
            /** Key */
            key: string;
            readiness: components["schemas"]["TicketReadinessSchema"];
        };
        /**
         * TicketDetailResponse
         * @description Operator-facing definition and execution state for one ticket.
         */
        TicketDetailResponse: {
            /** Acceptance Criteria */
            acceptance_criteria: string[];
            /** Completed At */
            completed_at: string | null;
            /** Component */
            component: string | null;
            /** Context */
            context: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition Of Done */
            definition_of_done: string[];
            /** Documentation Requirements */
            documentation_requirements: string[];
            /** Estimated Effort */
            estimated_effort: number | null;
            /** External Github Issue Id */
            external_github_issue_id: string | null;
            /** External Linear Id */
            external_linear_id: string | null;
            /** Implementation Notes */
            implementation_notes: string[];
            /** Key */
            key: string;
            /** Non Goals */
            non_goals: string[];
            /** Objective */
            objective: string;
            /** Priority */
            priority: number;
            /** Relevant Docs */
            relevant_docs: string[];
            risk_level: components["schemas"]["RiskLevel"];
            /** Source Anchor */
            source_anchor: string;
            status: components["schemas"]["TicketStatus"];
            /** Tags */
            tags: string[];
            /** Test Requirements */
            test_requirements: string[];
            ticket_type: components["schemas"]["TicketType"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TicketEvidenceItemSchema
         * @description One stored evidence row exposed without raw payload material.
         */
        TicketEvidenceItemSchema: {
            /** Has System Pin Triple */
            has_system_pin_triple: boolean;
            status: components["schemas"]["EvidenceStatus"];
            tier: components["schemas"]["ActorType"];
            type: components["schemas"]["EvidenceType"];
        };
        /**
         * TicketEvidenceResponse
         * @description Stored evidence for one ticket.
         */
        TicketEvidenceResponse: {
            /** Evidence */
            evidence: components["schemas"]["TicketEvidenceItemSchema"][];
        };
        /**
         * TicketReadinessSchema
         * @description Readiness verdict for one ticket.
         */
        TicketReadinessSchema: {
            /** Ready */
            ready: boolean;
            /** Reasons */
            reasons: components["schemas"]["NotReadyReasonSchema"][];
        };
        /**
         * TicketStatus
         * @description Lifecycle of a ticket (data-model §3.4).
         * @enum {string}
         */
        TicketStatus: "backlog" | "planned" | "blocked" | "ready_for_agent" | "in_progress" | "pr_open" | "review_required" | "changes_requested" | "done" | "rejected" | "needs_human_decision";
        /**
         * TicketType
         * @description Kind of work a ticket represents (data-model §3.4).
         * @enum {string}
         */
        TicketType: "feature" | "bug" | "tech_debt" | "spike" | "documentation" | "infrastructure" | "research";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationCheckType
         * @description Which Verification Engine check a row records (data-model §5.1).
         *
         *     A model-specific enum, defined with its model like EvidenceType — not a
         *     §2 shared type — and used by VerificationCheck, VerificationCheckRepo,
         *     and the rule-resolver. Members and values are verbatim from §5.1.
         * @enum {string}
         */
        VerificationCheckType: "acceptance_criteria" | "tests" | "lint" | "documentation" | "scope" | "security" | "human_approval";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dependency_critical_path_route_api_v1_dependencies_critical_path_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyCriticalPathResponse"];
                };
            };
            /** @description Stored dependency graph failed integrity validation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphValidationErrorResponse"];
                };
            };
        };
    };
    dependency_graph_route_api_v1_dependencies_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyGraphResponse"];
                };
            };
            /** @description Stored dependency graph failed integrity validation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphValidationErrorResponse"];
                };
            };
        };
    };
    list_epics_api_v1_epics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpicsResponse"];
                };
            };
        };
    };
    list_lessons_api_v1_lessons_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["EntityStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_lesson_api_v1_lessons__lesson_id__promote_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteLessonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionConflictResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
        };
    };
    reject_lesson_api_v1_lessons__lesson_id__reject_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectLessonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionConflictResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDispositionErrorResponse"];
                };
            };
        };
    };
    list_reviews_api_v1_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueResponse"];
                };
            };
        };
    };
    read_operator_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponse"];
                };
            };
        };
    };
    create_operator_session_api_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_operator_session_api_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponse"];
                };
            };
        };
    };
    read_system_status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    list_tickets_api_v1_tickets_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketBoardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticket_detail_api_v1_tickets__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticket_dependency_state_api_v1_tickets__key__dependencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDependenciesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticket_evidence_records_api_v1_tickets__key__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticket_count_api_v1_tickets_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCountResponse"];
                };
            };
        };
    };
}
