// This file is generated by atlas.tools.operator_ui_openapi.
// Do not edit it by hand.

export const atlasOpenApiEnums = {
  "AcceptanceConfirmationValidationCode": [
    "session_unknown",
    "criteria_fingerprint_mismatch",
    "manual_approval_required",
    "missing_criterion_index",
    "duplicate_criterion_index",
    "unknown_criterion_index",
    "extra_criterion_index"
  ],
  "AcceptanceSessionBlockingReason": [
    "pr_unknown",
    "pr_merged",
    "pr_closed",
    "pr_draft",
    "pr_fork_head",
    "pr_non_main",
    "integration_behind",
    "integration_diverged",
    "integration_conflicted",
    "integration_indeterminate",
    "external_state_indeterminate",
    "close_set_empty",
    "unknown_ticket",
    "ticket_not_review_required",
    "active_session_exists",
    "idempotency_key_reused",
    "repository_mismatch",
    "pr_number_mismatch",
    "head_ref_mismatch",
    "head_sha_mismatch",
    "head_repository_mismatch",
    "base_ref_mismatch",
    "base_sha_mismatch",
    "base_repository_mismatch",
    "close_set_mismatch",
    "eligibility_mismatch",
    "integration_status_mismatch",
    "criteria_mismatch",
    "session_stale",
    "evidence_not_ready",
    "confirmations_not_ready",
    "verification_not_passed",
    "session_unknown",
    "session_not_verifiable",
    "verification_already_completed",
    "verification_pending",
    "verification_failed",
    "verification_warning",
    "verification_not_applicable",
    "verification_malformed",
    "verification_close_set_mismatch",
    "verified_head_invalid",
    "verified_head_mismatch",
    "stored_history_invalid",
    "readiness_persistence_failed",
    "external_read_timeout",
    "external_response_malformed",
    "external_read_failed"
  ],
  "AcceptanceSessionLifecycle": [
    "preflight_passed",
    "evidence_ready",
    "confirmations_ready",
    "verification_passed",
    "merge_ready",
    "stale",
    "blocked",
    "failed"
  ],
  "AcceptanceSessionStep": [
    "preflight",
    "evidence",
    "confirmations",
    "verification",
    "readiness"
  ],
  "AcceptanceSessionStepState": [
    "pending",
    "complete",
    "blocked",
    "failed"
  ],
  "ActorType": [
    "human",
    "agent",
    "system"
  ],
  "AdmissionDecisionType": [
    "admit",
    "hold"
  ],
  "AdmissionHoldCode": [
    "policy_paused",
    "policy_draining",
    "snapshot_policy_mismatch",
    "snapshot_incomplete",
    "working_budget",
    "review_budget",
    "changes_requested_reserve",
    "risk_lane",
    "component_lane",
    "missing_external_linear_id",
    "single_write_limit"
  ],
  "AdmissionSyncReason": [
    "lease_unavailable",
    "product_ambiguous",
    "policy_unavailable",
    "snapshot_incomplete",
    "no_candidate",
    "policy_or_capacity_hold",
    "over_capacity",
    "revalidation_failed",
    "revalidation_mismatch",
    "policy_changed",
    "candidate_moved",
    "lease_lost",
    "write_confirmed",
    "write_indeterminate",
    "indeterminate_still_unresolved",
    "indeterminate_reconciled_admitted",
    "indeterminate_reconciled_no_write",
    "indeterminate_reconciled_moved"
  ],
  "DeliveryAdmissionMode": [
    "running",
    "paused",
    "draining"
  ],
  "DeliveryAdmissionPolicyConflictCode": [
    "stale_revision",
    "idempotency_key_reused",
    "in_progress"
  ],
  "DependencyType": [
    "depends_on",
    "relates_to",
    "implements",
    "supersedes"
  ],
  "EntityStatus": [
    "draft",
    "active",
    "archived",
    "deprecated"
  ],
  "EpicStatus": [
    "backlog",
    "planned",
    "in_progress",
    "done",
    "archived"
  ],
  "EvidenceStatus": [
    "pending",
    "passed",
    "failed",
    "warning",
    "not_applicable"
  ],
  "EvidenceType": [
    "test_result",
    "build_result",
    "lint_result",
    "coverage_report",
    "screenshot",
    "pr_review",
    "deployment_result",
    "documentation_update",
    "manual_approval",
    "pr_merged"
  ],
  "LessonCategory": [
    "success_pattern",
    "failure_pattern",
    "architecture",
    "testing",
    "delivery",
    "product",
    "research",
    "tech_debt"
  ],
  "NotReadyCode": [
    "wrong_status",
    "dependency_not_done",
    "adr_not_accepted",
    "no_acceptance_criteria",
    "dangling_target"
  ],
  "OccupancyDimension": [
    "working",
    "review",
    "risk_lane",
    "component_lane"
  ],
  "OperatorActionConflictCode": [
    "idempotency_key_reused",
    "in_progress",
    "stale_state"
  ],
  "OperatorActionFailureCode": [
    "command_failed",
    "receipt_commit_failed",
    "storage_failed"
  ],
  "OperatorActionOutcome": [
    "succeeded",
    "refused",
    "failed",
    "conflict"
  ],
  "OperatorActionResultCode": [
    "action_succeeded",
    "action_refused",
    "stale_state",
    "action_failed",
    "external_timeout",
    "evidence_transport_failed",
    "evidence_authentication_failed",
    "evidence_rate_limit_failed",
    "evidence_malformed_source",
    "action_conflict"
  ],
  "RiskLevel": [
    "low",
    "medium",
    "high",
    "critical"
  ],
  "SnapshotIncompletenessCode": [
    "incomplete_pull",
    "pagination_gap",
    "missing_issue_identity",
    "duplicate_issue_id",
    "duplicate_issue_identifier",
    "duplicate_atlas_join",
    "unmapped_state",
    "contradictory_state",
    "missing_external_linear_id",
    "missing_joined_issue",
    "missing_atlas_ticket",
    "atlas_linear_state_mismatch"
  ],
  "TicketStatus": [
    "backlog",
    "planned",
    "blocked",
    "ready_for_agent",
    "in_progress",
    "pr_open",
    "review_required",
    "changes_requested",
    "done",
    "rejected",
    "needs_human_decision"
  ],
  "TicketType": [
    "feature",
    "bug",
    "tech_debt",
    "spike",
    "documentation",
    "infrastructure",
    "research"
  ],
  "VerificationCheckType": [
    "acceptance_criteria",
    "tests",
    "lint",
    "documentation",
    "scope",
    "security",
    "human_approval"
  ]
} as const

export type AtlasOpenApiEnumName = keyof typeof atlasOpenApiEnums
